### ISSUE TITLE
Could not set capture. Internal Server Error

### ISSUE THREAD

**Issue by rikka-chunibyo** [Dreamsorcerer/bthidhub#34]
Keyboard visible on website, but shows up twice. If I click a check box it toggles both. Anyways it's not working on a 2015 iMac running macOS Monterey 12.7.6 21H1320.

The Raspberry Pi is a 2018 4B 8GB model. I tried with both a classic Dell keybaord and an Apple Magic Keyboard model A1644. I wasn't able to try wireless on the Apple keyboard as when I clicked "START SCANNING", a bunch of errors appeared saying it failed starting the scan.

After that happened the page stopped loading so I rebooted the Pi, now Bluetooth scanning works but won't find my Apple keyboard. When trying with my Dell keyboard I now get an error - "Could not set capture. Internal Server Error"

If there's logs for this program please make the location known.

Thank you.

**Comment by Dreamsorcerer** [comment]
> If there's logs for this program please make the location known.

You need to SSH into the RPi and run `journalctl -xeu remapper`. For Bluetooth connection issues, you might also want to check `journalctl -xeu bluetooth`.

**Comment by rikka-chunibyo** [comment]
Thank you, this is what I get when I start capturing the Dell keyboard

```
Feb 21 07:18:09 bthidhub systemd[1]: Started remapper.service - Remapper.
░░ Subject: A start job for unit remapper.service has finished successfully
░░ Defined-By: systemd
░░ Support: https://www.debian.org/support
░░ 
░░ A start job for unit remapper.service has finished successfully.
░░ 
░░ The job identifier is 119.
Feb 21 07:18:12 bthidhub python3[598]: Agent registered
Feb 21 07:18:12 bthidhub python3[598]: Removing all BT devices
Feb 21 07:18:12 bthidhub python3[598]: Adding all BT devices
Feb 21 18:17:39 bthidhub python3[598]: websocket connection opened
Feb 21 18:17:46 bthidhub python3[598]: HID Device  0003:413C:2113.0001  created
Feb 21 18:17:46 bthidhub python3[598]: HID Device  0003:413C:2113.0002  created
Feb 21 18:17:46 bthidhub python3[598]: Error handling request from 192.168.0.105
Feb 21 18:17:46 bthidhub python3[598]: Traceback (most recent call last):
Feb 21 18:17:46 bthidhub python3[598]:   File "/usr/local/lib/python3.11/dist-packages/aiohttp/web_protocol.py", line 480, in _handle_request
Feb 21 18:17:46 bthidhub python3[598]:     resp = await request_handler(request)
Feb 21 18:17:46 bthidhub python3[598]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Feb 21 18:17:46 bthidhub python3[598]:   File "/usr/local/lib/python3.11/dist-packages/aiohttp/web_app.py", line 569, in _handle
Feb 21 18:17:46 bthidhub python3[598]:     return await handler(request)
Feb 21 18:17:46 bthidhub python3[598]:            ^^^^^^^^^^^^^^^^^^^^^^
Feb 21 18:17:46 bthidhub python3[598]:   File "/usr/local/lib/python3.11/dist-packages/aiohttp/web_middlewares.py", line 117, in impl
Feb 21 18:17:46 bthidhub python3[598]:     return await handler(request)
Feb 21 18:17:46 bthidhub python3[598]:            ^^^^^^^^^^^^^^^^^^^^^^
Feb 21 18:17:46 bthidhub python3[598]:   File "/usr/local/lib/python3.11/dist-packages/aiohttp_session/__init__.py", line 191, in factory
Feb 21 18:17:46 bthidhub python3[598]:     response = await handler(request)
Feb 21 18:17:46 bthidhub python3[598]:                ^^^^^^^^^^^^^^^^^^^^^^
Feb 21 18:17:46 bthidhub python3[598]:   File "/home/pi/bthidhub/web.py", line 140, in set_device_capture
Feb 21 18:17:46 bthidhub python3[598]:     self.hid_devices.set_device_capture(device_id, capture_state)
Feb 21 18:17:46 bthidhub python3[598]:   File "/home/pi/bthidhub/hid_devices.py", line 384, in set_device_capture
Feb 21 18:17:46 bthidhub python3[598]:     self.__scan_devices()
Feb 21 18:17:46 bthidhub python3[598]:   File "/home/pi/bthidhub/hid_devices.py", line 361, in __scan_devices
Feb 21 18:17:46 bthidhub python3[598]:     for k in dev_config["mapped_ids"]:
Feb 21 18:17:46 bthidhub python3[598]:              ~~~~~~~~~~^^^^^^^^^^^^^^
Feb 21 18:17:46 bthidhub python3[598]: TypeError: list indices must be integers or slices, not str
pi@bthidhub:~ $ 
```

I haven't been able to replicate the problems I was having with Bluetooth so I don't have a log for that.

**Comment by Dreamsorcerer** [comment]
And then restart with `sudo systemctl restart remapper`

**Comment by rikka-chunibyo** [comment]
That's strange, there isn't even a config file

**Comment by rikka-chunibyo** [comment]
I'm also seeing [this](https://imgur.com/a/CmP5ZR3) now

**Comment by Dreamsorcerer** [comment]
> That's strange, there isn't even a config file

I don't think that'd be possible...
If so, you'll need to add some print()s to the code and inspect what is happening. That dev_config variable should be a dict, not a list (and it's assigned only a few lines before that if it's a fresh config).

**Comment by rikka-chunibyo** [comment]
```
pi@bthidhub:~/bthidhub $ sudo systemctl stop remapper
pi@bthidhub:~/bthidhub $ python remapper.py 
Agent registered
Removing all BT devices
Adding all BT devices
websocket connection opened
Error handling request from 192.168.0.105
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/aiohttp/web_protocol.py", line 480, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/aiohttp/web_app.py", line 569, in _handle
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/aiohttp_session/__init__.py", line 191, in factory
    response = await handler(request)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pi/bthidhub/web.py", line 140, in set_device_capture
    self.hid_devices.set_device_capture(device_id, capture_state)
  File "/home/pi/bthidhub/hid_devices.py", line 383, in set_device_capture
    self.__save_config()
  File "/home/pi/bthidhub/hid_devices.py", line 406, in __save_config
    with open(DEVICES_CONFIG_FILE_NAME, 'w') as devices_config_file:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
PermissionError: [Errno 13] Permission denied: 'devices_config.json'
```

Well I know why now, I assume you don't have the permissions set in the install then?

**Comment by rikka-chunibyo** [comment]
Ohh okay, that's weird because I think it's also not running as root when the Pi starts. I think it's failing to create the file not access it since the file is very much not there. I'll run it as root and see.

**Comment by Dreamsorcerer** [comment]
`ls -la /home/pi/bthidhub`?

**Comment by rikka-chunibyo** [comment]
```
pi@bthidhub:~ $ ls -la /home/pi/bthidhub
total 520
drwxrwxrwx 9 root root   4096 Feb 21 19:25 .
drwx------ 3 pi   pi     4096 Feb 21 18:17 ..
-rwxrwxrwx 1 root root  13091 Feb 21 06:42 adapter.py
-rwxrwxrwx 1 root root   4613 Feb 21 06:42 agent.py
-rwxrwxrwx 1 root root  12922 Feb 21 06:42 bluetooth_devices.py
-rwxrwxrwx 1 root root  90051 Feb 21 06:42 bthidhubarchitecture.png
-rwxrwxrwx 1 root root  55417 Feb 21 06:42 bt-hid-hub-bt-devices.png
-rwxrwxrwx 1 root root  39974 Feb 21 06:42 bt-hid-hub-devices.png
-rwxrwxrwx 1 root root 182588 Feb 21 06:42 bthidhuboverall.png
-rwxrwxrwx 1 root root   7973 Feb 21 06:42 compatibility_device.py
-rw-r--r-- 1 pi   pi      250 Feb 21 19:29 devices_config.json
drwxrwxrwx 2 root root   4096 Feb 21 06:42 filters
drwxr-xr-x 8 root root   4096 Feb 21 06:42 .git
drwxr-xr-x 3 root root   4096 Feb 21 06:42 .github
-rw-r--r-- 1 root root     80 Feb 21 06:42 .gitignore
drwxrwxrwx 3 root root   4096 Feb 21 06:42 install
-rwxrwxrwx 1 root root   1072 Feb 21 06:42 LICENSE
-rw-r--r-- 1 root root    741 Feb 21 06:42 .mypy.ini
-rwxrwxrwx 1 root root    563 Feb 21 06:42 password.py
drwxrwxrwx 2 root root   4096 Feb 21 06:48 __pycache__
-rwxrwxrwx 1 root root   4360 Feb 21 06:42 README.md
-rwxrwxrwx 1 root root    903 Feb 21 06:42 remapper.py
-rwxrwxrwx 1 root root    123 Feb 21 06:42 requirements.txt
-rwxrwxrwx 1 root root   2461 Feb 21 06:42 sdp_record_template.xml
drwxrwxrwx 4 root root   4096 Feb 21 06:42 stubs
drwxrwxrwx 4 root root   4096 Feb 21 06:42 web
-rwxrwxrwx 1 root root  10602 Feb 21 06:42 web.py
pi@bthidhub:~ $ 

```

**Comment by Dreamsorcerer** [comment]
Huh, you have the inverse...
pi owned config and root owned everything else.

**Comment by rikka-chunibyo** [comment]
Oh I guess I missed it the first time

**Comment by rikka-chunibyo** [comment]
Okay I'll try with chown first then reinstalling if it doesn't work. Thanks.

**Comment by rikka-chunibyo** [comment]
That's odd, it works now but I still get "Could not set capture. Internal Server Error"

```
Feb 21 19:34:42 bthidhub python3[608]: HID Device  0003:413C:2113.0002  created
Feb 21 19:34:42 bthidhub python3[608]: Error handling request from 192.168.0.105
Feb 21 19:34:42 bthidhub python3[608]: Traceback (most recent call last):
Feb 21 19:34:42 bthidhub python3[608]:   File "/usr/local/lib/python3.11/dist-packages/aiohttp/web_protocol.py", line 480, in _handle_request
Feb 21 19:34:42 bthidhub python3[608]:     resp = await request_handler(request)
Feb 21 19:34:42 bthidhub python3[608]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Feb 21 19:34:42 bthidhub python3[608]:   File "/usr/local/lib/python3.11/dist-packages/aiohttp/web_app.py", line 569, in _handle
Feb 21 19:34:42 bthidhub python3[608]:     return await handler(request)
Feb 21 19:34:42 bthidhub python3[608]:            ^^^^^^^^^^^^^^^^^^^^^^
Feb 21 19:34:42 bthidhub python3[608]:   File "/usr/local/lib/python3.11/dist-packages/aiohttp/web_middlewares.py", line 117, in impl
Feb 21 19:34:42 bthidhub python3[608]:     return await handler(request)
Feb 21 19:34:42 bthidhub python3[608]:            ^^^^^^^^^^^^^^^^^^^^^^
Feb 21 19:34:42 bthidhub python3[608]:   File "/usr/local/lib/python3.11/dist-packages/aiohttp_session/__init__.py", line 191, in factory
Feb 21 19:34:42 bthidhub python3[608]:     response = await handler(request)
Feb 21 19:34:42 bthidhub python3[608]:                ^^^^^^^^^^^^^^^^^^^^^^
Feb 21 19:34:42 bthidhub python3[608]:   File "/home/pi/bthidhub/web.py", line 140, in set_device_capture
Feb 21 19:34:42 bthidhub python3[608]:     self.hid_devices.set_device_capture(device_id, capture_state)
Feb 21 19:34:42 bthidhub python3[608]:   File "/home/pi/bthidhub/hid_devices.py", line 384, in set_device_capture
Feb 21 19:34:42 bthidhub python3[608]:     self.__scan_devices()
Feb 21 19:34:42 bthidhub python3[608]:   File "/home/pi/bthidhub/hid_devices.py", line 361, in __scan_devices
Feb 21 19:34:42 bthidhub python3[608]:     for k in dev_config["mapped_ids"]:
Feb 21 19:34:42 bthidhub python3[608]:              ~~~~~~~~~~^^^^^^^^^^^^^^
Feb 21 19:34:42 bthidhub python3[608]: TypeError: list indices must be integers or slices, not str
```

**Comment by rikka-chunibyo** [comment]
Now I'm even more lost, after a reboot I now get this and the web interface isn't up

```
Feb 21 19:39:57 bthidhub python3[736]: HID Device  0003:413C:2113.0001  created
Feb 21 19:39:57 bthidhub python3[736]: HID Device  0003:413C:2113.0002  created
Feb 21 19:39:57 bthidhub python3[736]: Traceback (most recent call last):
Feb 21 19:39:57 bthidhub python3[736]:   File "/home/pi/bthidhub/remapper.py", line 22, in <module>
Feb 21 19:39:57 bthidhub python3[736]:     hid_devices = HIDDeviceRegistry(loop)
Feb 21 19:39:57 bthidhub python3[736]:                   ^^^^^^^^^^^^^^^^^^^^^^^
Feb 21 19:39:57 bthidhub python3[736]:   File "/home/pi/bthidhub/hid_devices.py", line 248, in __init__
Feb 21 19:39:57 bthidhub python3[736]:     self.__scan_devices()
Feb 21 19:39:57 bthidhub python3[736]:   File "/home/pi/bthidhub/hid_devices.py", line 361, in __scan_devices
Feb 21 19:39:57 bthidhub python3[736]:     for k in dev_config["mapped_ids"]:
Feb 21 19:39:57 bthidhub python3[736]:              ~~~~~~~~~~^^^^^^^^^^^^^^
Feb 21 19:39:57 bthidhub python3[736]: TypeError: list indices must be integers or slices, not str
Feb 21 19:39:58 bthidhub systemd[1]: remapper.service: Main process exited, code=exited, status=1/FAILURE
░░ Subject: Unit process exited
░░ Defined-By: systemd
░░ Support: https://www.debian.org/support
░░ 
░░ An ExecStart= process belonging to unit remapper.service has exited.
░░ 
░░ The process' exit code is 'exited' and its exit status is 1.
Feb 21 19:39:58 bthidhub systemd[1]: remapper.service: Failed with result 'exit-code'.
░░ Subject: Unit failed
░░ Defined-By: systemd
░░ Support: https://www.debian.org/support
░░ 
░░ The unit remapper.service has entered the 'failed' state with result 'exit-code'.
Feb 21 19:39:58 bthidhub systemd[1]: remapper.service: Consumed 1.632s CPU time.
░░ Subject: Resources consumed by unit runtime
░░ Defined-By: systemd
░░ Support: https://www.debian.org/support
░░ 
░░ The unit remapper.service completed and consumed the indicated resources.
```

Sorry to bug you so much about this

**Comment by rikka-chunibyo** [comment]
Should I be running the installer as root or pi?

**Comment by Dreamsorcerer** [comment]
What installer exactly?
If you mean the setup.sh script, it is run as pi when following the instructions:
https://github.com/Dreamsorcerer/bthidhub?tab=readme-ov-file#install-instructions

**Comment by rikka-chunibyo** [comment]
Right. I'm gonna try reinstalling the operating system too, I can't think of anything else to try.

**Comment by rikka-chunibyo** [comment]
I get this while installing then it hangs for a while (got it last time too) `sudo: unable to resolve host rpi-hid: Name or service not known`, it continues seemingly fine though.

`Failed to load update bluetooth devices list. Internal Server Error` when clicking the capture box (also 2 of them still show up)

```
 21 20:19:13 bthidhub sudo[737]:     root : PWD=/home/pi/bthidhub ; USER=root ; COMMAND=/usr/bin/hcitool lp 28:F0:76:4A:E4:F5 sniff
Feb 21 20:19:13 bthidhub sudo[737]: pam_unix(sudo:session): session opened for user root(uid=0) by (uid=0)
Feb 21 20:19:13 bthidhub sudo[737]: pam_unix(sudo:session): session closed for user root
Feb 21 20:19:17 bthidhub sudo[740]:     root : PWD=/home/pi/bthidhub ; USER=root ; COMMAND=/usr/bin/hcitool con
Feb 21 20:19:17 bthidhub sudo[740]: pam_unix(sudo:session): session opened for user root(uid=0) by (uid=0)
Feb 21 20:19:17 bthidhub sudo[740]: pam_unix(sudo:session): session closed for user root
Feb 21 20:19:17 bthidhub sudo[743]:     root : PWD=/home/pi/bthidhub ; USER=root ; COMMAND=/usr/bin/hcitool sr 28:F0:76:4A:E4:F5 master
Feb 21 20:19:17 bthidhub sudo[743]: pam_unix(sudo:session): session opened for user root(uid=0) by (uid=0)
Feb 21 20:19:17 bthidhub python3[745]: Switch role request failed: Input/output error
Feb 21 20:19:17 bthidhub sudo[743]: pam_unix(sudo:session): session closed for user root
Feb 21 20:19:17 bthidhub python3[608]: hcitool  28:F0:76:4A:E4:F5  success: False
Feb 21 20:19:17 bthidhub sudo[746]:     root : PWD=/home/pi/bthidhub ; USER=root ; COMMAND=/usr/bin/hcitool lp 28:F0:76:4A:E4:F5 sniff
Feb 21 20:19:17 bthidhub sudo[746]: pam_unix(sudo:session): session opened for user root(uid=0) by (uid=0)
Feb 21 20:19:17 bthidhub sudo[746]: pam_unix(sudo:session): session closed for user root
Feb 21 20:19:18 bthidhub sudo[749]:     root : PWD=/home/pi/bthidhub ; USER=root ; COMMAND=/usr/bin/hcitool con
Feb 21 20:19:18 bthidhub sudo[749]: pam_unix(sudo:session): session opened for user root(uid=0) by (uid=0)
Feb 21 20:19:18 bthidhub sudo[749]: pam_unix(sudo:session): session closed for user root
Feb 21 20:19:18 bthidhub sudo[752]:     root : PWD=/home/pi/bthidhub ; USER=root ; COMMAND=/usr/bin/hcitool sr 28:F0:76:4A:E4:F5 master
Feb 21 20:19:18 bthidhub sudo[752]: pam_unix(sudo:session): session opened for user root(uid=0) by (uid=0)
Feb 21 20:19:18 bthidhub python3[754]: Switch role request failed: Input/output error
Feb 21 20:19:18 bthidhub sudo[752]: pam_unix(sudo:session): session closed for user root
Feb 21 20:19:18 bthidhub python3[608]: hcitool  28:F0:76:4A:E4:F5  success: False
Feb 21 20:19:18 bthidhub sudo[755]:     root : PWD=/home/pi/bthidhub ; USER=root ; COMMAND=/usr/bin/hcitool lp 28:F0:76:4A:E4:F5 sniff
Feb 21 20:19:18 bthidhub sudo[755]: pam_unix(sudo:session): session opened for user root(uid=0) by (uid=0)
Feb 21 20:19:18 bthidhub sudo[755]: pam_unix(sudo:session): session closed for user root
Feb 21 20:19:19 bthidhub python3[608]: HID Device  0003:413C:2113.0001  created
Feb 21 20:19:19 bthidhub python3[608]: HID Device  0003:413C:2113.0002  created
Feb 21 20:19:19 bthidhub python3[608]: device_connected_state_changed
Feb 21 20:19:19 bthidhub python3[608]: Error handling request from 192.168.0.105
Feb 21 20:19:19 bthidhub python3[608]: Traceback (most recent call last):
Feb 21 20:19:19 bthidhub python3[608]:   File "/usr/local/lib/python3.11/dist-packages/aiohttp/web_protocol.py", line 480, in _handle_request
Feb 21 20:19:19 bthidhub python3[608]:     resp = await request_handler(request)
Feb 21 20:19:19 bthidhub python3[608]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Feb 21 20:19:19 bthidhub python3[608]:   File "/usr/local/lib/python3.11/dist-packages/aiohttp/web_app.py", line 569, in _handle
Feb 21 20:19:19 bthidhub python3[608]:     return await handler(request)
Feb 21 20:19:19 bthidhub python3[608]:            ^^^^^^^^^^^^^^^^^^^^^^
Feb 21 20:19:19 bthidhub python3[608]:   File "/usr/local/lib/python3.11/dist-packages/aiohttp/web_middlewares.py", line 117, in impl
Feb 21 20:19:19 bthidhub python3[608]:     return await handler(request)
Feb 21 20:19:19 bthidhub python3[608]:            ^^^^^^^^^^^^^^^^^^^^^^
Feb 21 20:19:19 bthidhub python3[608]:   File "/usr/local/lib/python3.11/dist-packages/aiohttp_session/__init__.py", line 191, in factory
Feb 21 20:19:19 bthidhub python3[608]:     response = await handler(request)
Feb 21 20:19:19 bthidhub python3[608]:                ^^^^^^^^^^^^^^^^^^^^^^
Feb 21 20:19:19 bthidhub python3[608]:   File "/home/pi/bthidhub/web.py", line 195, in get_bluetooth_devices
Feb 21 20:19:19 bthidhub python3[608]:     return web.Response(text=json.dumps(self.adapter.get_devices()))
Feb 21 20:19:19 bthidhub python3[608]:                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^
Feb 21 20:19:19 bthidhub python3[608]:   File "adapter.py", line 223, in get_devices
Feb 21 20:19:19 bthidhub python3[608]:     return {"devices": devices, "scanning": self.adapter.Discovering}
Feb 21 20:19:19 bthidhub python3[608]:   File "/usr/local/lib/python3.11/dist-packages/dasbus/client/proxy.py", line 164, in __getattr__
Feb 21 20:19:19 bthidhub python3[608]:     return member.get()
Feb 21 20:19:19 bthidhub python3[608]:            ^^^^^^^^^^^^
Feb 21 20:19:19 bthidhub python3[608]:   File "/usr/local/lib/python3.11/dist-packages/dasbus/client/property.py", line 43, in get
Feb 21 20:19:19 bthidhub python3[608]:     return self.__get__(None, None)  # pylint: disable=unnecessary-dunder-call
Feb 21 20:19:19 bthidhub python3[608]:            ^^^^^^^^^^^^^^^^^^^^^^^^
Feb 21 20:19:19 bthidhub python3[608]:   File "/usr/local/lib/python3.11/dist-packages/dasbus/client/property.py", line 54, in __get__
Feb 21 20:19:19 bthidhub python3[608]:     return self._getter()
Feb 21 20:19:19 bthidhub python3[608]:            ^^^^^^^^^^^^^^
Feb 21 20:19:19 bthidhub python3[608]:   File "/usr/local/lib/python3.11/dist-packages/dasbus/client/handler.py", line 382, in _get_property_value
Feb 21 20:19:19 bthidhub python3[608]:     variant = self._call_method(
Feb 21 20:19:19 bthidhub python3[608]:               ^^^^^^^^^^^^^^^^^^
Feb 21 20:19:19 bthidhub python3[608]:   File "/usr/local/lib/python3.11/dist-packages/dasbus/client/handler.py", line 450, in _call_method
Feb 21 20:19:19 bthidhub python3[608]:     return self._get_method_reply(
Feb 21 20:19:19 bthidhub python3[608]:            ^^^^^^^^^^^^^^^^^^^^^^^
Feb 21 20:19:19 bthidhub python3[608]:   File "/usr/local/lib/python3.11/dist-packages/dasbus/client/handler.py", line 483, in _get_method_reply
Feb 21 20:19:19 bthidhub python3[608]:     return self._handle_method_error(error)
Feb 21 20:19:19 bthidhub python3[608]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Feb 21 20:19:19 bthidhub python3[608]:   File "/usr/local/lib/python3.11/dist-packages/dasbus/client/handler.py", line 509, in _handle_method_error
Feb 21 20:19:19 bthidhub python3[608]:     raise exception from None
Feb 21 20:19:19 bthidhub python3[608]: dasbus.error.DBusError: Method "Get" with signature "ss" on interface "org.freedesktop.DBus.Properties" doesn't exist
Feb 21 20:19:19 bthidhub python3[608]: Bluetooth adapter removed. Stopping
Feb 21 20:19:20 bthidhub python3[608]: Agent Release
Feb 21 20:19:20 bthidhub python3[608]: Bluetooth adapter removed. Stopping
Feb 21 20:19:20 bthidhub python3[608]: Bluetooth adapter added. Starting
Feb 21 20:19:20 bthidhub python3[608]: Bluetooth adapter added. Starting
Feb 21 20:19:20 bthidhub python3[608]: Bluetooth adapter added. Starting
```

**Comment by Dreamsorcerer** [comment]
> I get this while installing then it hangs for a while (got it last time too) `sudo: unable to resolve host rpi-hid: Name or service not known`, it continues seemingly fine though.

I don't see rpi-hid mentioned anywhere in this project, so really not sure how you're getting that.
One of the last commands in the installation will set the hostname to bthidhub:
https://github.com/Dreamsorcerer/bthidhub/blob/0172b35c64efcedf7f2eeb74bb87d554042e79f5/install/on_rpi/on_pi_setup.sh#L39

I've not seen the dbus error before, are you sure you flashed the card with bookworm?

**Comment by rikka-chunibyo** [comment]
Using Raspberry Pi Imager I flashed it with Raspberry Pi OS Lite (32-bit), just like the readme says too. The description says it's Debian Bookworm still.

**Comment by rikka-chunibyo** [comment]
Seems so, a few restarts later got me to the point where I'm back at `KeyError: '_'`

**Comment by Dreamsorcerer** [comment]
compatibility mode probably needs to be removed, I don't think it has any use now.

**Comment by Dreamsorcerer** [comment]
Wait, your device might have multiple descriptors...

**Comment by rikka-chunibyo** [comment]
That would explain why it shows up twice, I'll try a few other keyboards

**Comment by rikka-chunibyo** [comment]
Okay, I tried with some old Android keyboard I soldered a usb port to, and it works. The touchpad on it doesn't though. What's strange is it still shows up twice

**Comment by Dreamsorcerer** [comment]
Ah, then yes. That messes with the system currently as both descriptors get under the same ID.
#26 is supposed to fix it, but it currently breaks everything when I try it.

**Comment by rikka-chunibyo** [comment]
Ohh alright. Apple keyboard also doesn't work by the way.

**Comment by Dreamsorcerer** [comment]
> Okay, I tried with some old Android keyboard I soldered a usb port to, and it works. The touchpad on it doesn't though. What's strange is it still shows up twice

Yeah, expect flakiness if it shows up twice. It might be on this device that it's using the second descriptor, and that one has the keyboard, but not trackpad. But, reconnecting the device may cause the BT to restart etc. so expect flakiness.

**Comment by rikka-chunibyo** [comment]
Okay, I would like to be able to use the Apple keyboard though, is there any even temporary fix that I could use?

**Comment by Dreamsorcerer** [comment]
Does that appear twice? If not, I'd expect it to work (maybe ensure the doubled devices have capture disabled though).

You can also try out the code in that PR and see if it works for you (it presumably worked for the author). You can just add the git remote and checkout their code (which is what I've done while testing it).

**Comment by rikka-chunibyo** [comment]
Yes, the Apple keyboard appears twice. But unlike the Android keyboard (which also shows up twice), the Apple keyboard doesn't work.

Okay, I guess I can try it. Thanks

**Comment by Dreamsorcerer** [comment]
Yeah, in that case, it descriptor being used is presumably the one without the keyboard events (at a guess, it might report a separate device for the battery information, or some Mac specific functionality).

It's just down to the ordering of the descriptors as to which one ends up being used.

**Comment by rikka-chunibyo** [comment]
So is pr 26 just using a different system for ids?

**Comment by Dreamsorcerer** [comment]
It looks like it. Specifically, it uses a hash of the descriptor as part of the ID, rather than only the device class. So, it can record both descriptors as separate devices, whereas currently when it sees the second descriptor with the same device class it just overwrites the previous one.

Problem is that when I try the code, I get no events at all for all my devices which don't use multiple descriptors (and I thought that it was a lot rarer to have multiple device descriptors, but clearly I was wrong). When I have the time to figure out why it breaks, then I can hopefully get that merged in and fully working.

**Comment by rikka-chunibyo** [comment]
I haven't really gone through the code that deeply at all, so this is just a quick thought but is there any change simply using the old code for devices with 1 descriptor can resolve that? It wouldn't be a great solution but sounds to me like it would work for a quick fix.

**Comment by Dreamsorcerer** [comment]
Maybe, but I'd really need to know what the cause of the failure is first. I also didn't actually test with a device that has multiple descriptors, so I'd need to check that atleast works for me too.

**Comment by rikka-chunibyo** [comment]
Oh okay. If you don't have any devices with multiple descriptors I have a ton so I'm always open to test for you if you ever need it

**Comment by Dreamsorcerer** [comment]
I have one small mouse in the back of a drawer that does for some reason, so I'll get it out later and test again.

**Comment by rikka-chunibyo** [comment]
Alright, thanks for going through this entire proccess with me so far, maybe you should throw a quick warning or something up in the readme or on the web interface that it currently doesn't work with devices that have multiple descriptors. Just to prevent more issues like this happening haha

**Comment by rikka-chunibyo** [comment]
Okay, so the pr worked. The Apple keyboard still shows up as 2 devices under the same name, but I can now toggle them individually. Toggling the top one seemingly does nothing (doesn't even block the input on the terminal, which your code did), toggling the bottom one however works perfectly. What you meantioned previously where it doesn't work with devices that have one descriptor seems accurate, as teh Android keyboard doesn't work at all now (I really don't care about that keyboard but it'd obviously affect other devices as well). So all that's left is to make the pr work with single descriptor devices!

**Comment by Dreamsorcerer** [comment]
> My mouse works too but it's SUPER slow and choppy.

If you have access to a Raspberry Pi Zero, it'd be worth testing on that. I assumed that older Pi models were causing a problem, but I think the Zero is the only model that's been confirmed to work well so far...

Also, you can try recompiling the code on the new PR:
```
cd /home/pi/bthidhub/
mypyc
sudo systemctl restart remapper
```

**Comment by Dreamsorcerer** [comment]
> Remapping my keyboard via Apple's Modifier Key's button in keyboard preferences also doesn't work properly

I don't know how that works, but if it's using some custom Mac code, then it may not work as the device is not advertised as a Mac keyboard anymore. If you want to mess around with filters though, you can have the Pi do the remapping (which also ensures that it works the same way on all hosts).
https://github.com/Dreamsorcerer/bthidhub/tree/master/filters

**Comment by rikka-chunibyo** [comment]
Oh I just reran the setup.sh file and it seemed to work fine, for some reason it didn't occur to me that I could just recompile lol. I don't have access to a Zero at the moment but I have been thinking about buying one. The specs are better on my Pi (4B 8GB Model) than the Pi Zero W, so if it's about specs than I don't think that's the problem, otherwise yeah hardware would probably make a difference.

Would I have to manually install filters or what? Currently there's no filters in the list on the web interface

**Comment by rikka-chunibyo** [comment]
How does switching between computers work? Is it specific to your Apple keyboard as it doesn't do anything when I try

**Comment by Dreamsorcerer** [comment]
> The specs are better on my Pi (4B 8GB Model) than the Pi Zero W, so if it's about specs than I don't think that's the problem

Yeah, that's what I'm confused by, I've no idea what the difference is. We had a previous report that the Pi 2 is moderately laggy and I guessed it might be performance as it has a 900Mhz CPU vs the Zero's 1GHz. But, the Pi 4 should be significantly faster...

Thinking back to other times I've had lag, there is the possibility it failed to set the device to master mode...
You should see these print statements in the journalctl log:
https://github.com/Dreamsorcerer/bthidhub/blob/0172b35c64efcedf7f2eeb74bb87d554042e79f5/bluetooth_devices.py#L215-L220

You can also use hcitool on the Pi to inspect the connection. You're looking for the laptop and verifying that it's set to MASTER and not SLAVE (or similar terminology).

**Comment by Dreamsorcerer** [comment]
> How does switching between computers work? Is it specific to your Apple keyboard as it doesn't do anything when I try

Uh, to be honest, I haven't worked on that yet on the revamped codebase. I need to test it out and create a UI for it.
You can probably make it work with a filter than returns `b"\xFF"` when you want to switch, which will get caught here:
https://github.com/Dreamsorcerer/bthidhub/blob/0172b35c64efcedf7f2eeb74bb87d554042e79f5/hid_devices.py#L174-L176

That's how ruundii was doing it in the legacy code:
https://github.com/Dreamsorcerer/bthidhub/blob/1aacf269db3be96b6e2d38af21ad2f0a12cad563/a1314_message_filter.py#L113-L115

**Comment by rikka-chunibyo** [comment]
Oh alright, I think that's honestly one of the best features. It allows you to not only make your keyboard and mouse wireless, but also emulates a KVM (without the video) but without using extra usb cables for each computer, love that!

**Comment by rikka-chunibyo** [comment]
> Hang on, that makes a lot of sense actually, I believe the Pi 4B handles that differently as the Pi itself can't be set to slave mode when connecting to a computer via USB, maybe that's something to look into? Then again it's not slave mdoe that it's beign set to so I'm not really sure on that. If it makes any difference I'm using a 2015 iMac, not a modern mac laptop as it's the only thing I have where I am right now, don't have access to my desktop or laptop.
> 
> Anyways I think your on to something - this pretty much gets spammed in the console, not sure if it's constant or only when a USB event occurs
> 
> ```
> Feb 21 22:05:02 bthidhub sudo[5542]:     root : PWD=/home/pi/bthidhub ; USER=root ; COMMAND=/usr/bin/hcitool sr 28:F0:76:4A:E4:F5 master
> Feb 21 22:05:02 bthidhub sudo[5542]: pam_unix(sudo:session): session opened for user root(uid=0) by (uid=0)
> Feb 21 22:05:02 bthidhub python3[5544]: Switch role request failed: Input/output error
> Feb 21 22:05:02 bthidhub sudo[5542]: pam_unix(sudo:session): session closed for user root
> Feb 21 22:05:02 bthidhub python3[597]: hcitool  28:F0:76:4A:E4:F5  success: False
> ```
> 
> **`Switch role request failed: Input/output error`**

Posting this just to make sure you saw the other comment (pretty hard to miss though)

**Comment by Dreamsorcerer** [comment]
> Anyways I think your on to something - this pretty much gets spammed in the console, not sure if it's constant or only when a USB event occurs

That loop retries every 5 seconds, which probably isn't the most useful approach...
Try running the command yourself though to confirm it's not an issue with the application.
Looks like you'd want to do `sudo hcitool sr 28:F0:76:4A:E4:F5 master`

**Comment by rikka-chunibyo** [comment]
Yeah, same result. Not the application
```
pi@bthidhub:~/bthidhub/filters $ sudo hcitool sr 28:F0:76:4A:E4:F5 master
Switch role request failed: Input/output error
```

**Comment by Dreamsorcerer** [comment]
Yeah, I don't know enough about hcitool to give you any further advise on that point. Weird if the Zero can do it, but the 4 can't...

**Comment by rikka-chunibyo** [comment]
Could also be something with the Apple keyboard I have, I didn't even know that tool existed before now so I'm no help on that front

**Comment by rikka-chunibyo** [comment]
> [bthidhub/a1314_message_filter.py](https://github.com/Dreamsorcerer/bthidhub/blob/1aacf269db3be96b6e2d38af21ad2f0a12cad563/a1314_message_filter.py#L113-L115)
> 
> Lines 113 to 115 in [1aacf26](/Dreamsorcerer/bthidhub/commit/1aacf269db3be96b6e2d38af21ad2f0a12cad563)
> 
>  if result_report == b'\x01\x05\x00\x2b\x00\x00\x00\x00\x00': 
>      print("host switch") 
>      return b'\xff'

How can I turn this into a filter with the new system?

**Comment by Dreamsorcerer** [comment]
> Oh alright, I think that's honestly one of the best features. It allows you to not only make your keyboard and mouse wireless, but also emulates a KVM (without the video) but without using extra usb cables for each computer, love that!

Yeah, absolutely. But, I spent most of December getting devices to "just work" (apparently only single-descriptor ones..), so havent had the time to clean up the other features. The old project was an absolute nightmare, if you look at those legacy filters, they are incredibly convoluted and you needed a different one for every device. The only way to get the project functioning was to spend hours (probably days) looking a device descriptors and trying to translate them..

**Comment by rikka-chunibyo** [comment]
Oh yeah that sounds painful, I'm quite glad you ended up getting the project working though (even if not all of it), it's an amazing project

**Comment by Dreamsorcerer** [comment]
> > [bthidhub/a1314_message_filter.py](https://github.com/Dreamsorcerer/bthidhub/blob/1aacf269db3be96b6e2d38af21ad2f0a12cad563/a1314_message_filter.py#L113-L115)
> > Lines 113 to 115 in [1aacf26](/Dreamsorcerer/bthidhub/commit/1aacf269db3be96b6e2d38af21ad2f0a12cad563)
> > if result_report == b'\x01\x05\x00\x2b\x00\x00\x00\x00\x00':
> > print("host switch")
> > return b'\xff'
> 
> How can I turn this into a filter with the new system?

Look through the README in the filters/ directory. For something that simple, you won't need to learn anything about descriptors, you can just print() the message to find the message you want and then do a filter just like that.

i.e.
```
def message_filter(msg: bytes) -> bytes:
    if msg == <your-message>:
        return b"\xFF"
    return msg
```

**Comment by rikka-chunibyo** [comment]
Great, I believe that worked, it's at least printing out a quick message I added.

**Comment by rikka-chunibyo** [comment]
Would you ever considering making it so you can select multiple filters on one device, and just set the priority or order them? That would allow people to make different filters and change which ones are enabled modifying any code or even restarting anything.

**Comment by Dreamsorcerer** [comment]
I'm not really sure how much benefit that would add, or what use case there'd be. It'd likely also create conflicts if those filters don't know about what the other filters are doing...

**Comment by rikka-chunibyo** [comment]
Which is why there'd be a priority system. Anyways I understand what you mean, it probably wouldn't be used much. I might make a quick janky version for personal use then lol

**Comment by Dreamsorcerer** [comment]
I don't really see how you'd decide the priority though. If you understand enough to set the order of filters, you probably know enough to put the code into a single function.

**Comment by rikka-chunibyo** [comment]
Oh for sure I do but I just think it'd be a nice touch to be able to set multiple filters in whatever order I want so I'd be able to do something like apply the KVM filter and another filter for remapping keys or something like that without having to combine them. It's easy enough to combine them but I'll probably be making a lot of filters it would become a hassle

**Comment by Dreamsorcerer** [comment]
Bear in mind the filters are modifying the reports of each unique device, so it's also not like you can mix and match filters across different devices.

> apply the KVM filter and another filter for remapping keys or something like that without having to combine them

I think if you want to abstract them to keep them more maintainable, you should just use functions or methods to do so. I see no reason for anything more complex. You have a full Python module to create your filter, so I'd just do something like:
```
def host_switch(msg):
    ...

def remap_keys(msg):
    ...

def message_filter(msg):
    msg = host_switch(msg)
    return remap_keys(msg)
```

You could also do something like (which roughly does what you suggested, it just can't be reordered in the UI dynamically):
```
from functools import partial, reduce

filters = (host_switch, remap_keys)

message_filter = partial(reduce, lambda msg, f: f(msg), filters)
```

There's also an example in the readme of using a class to track state, which might be useful.

**Comment by rikka-chunibyo** [comment]
Makes sense, thanks for the examples. I was thinking more like the same dropdown, but every time you choose one another dropdown appears next to it so you can add more filters or something similar to that, making the priorty the order they are selected in. This would also allow you to have seperate filters for different things, if one is interfering with something you are trying to do, simply disable that filter, instead of going through the code and commenting it out or removing it or however else you could disable it. The main focus of my idea is the ease of disabling seperate filters rather than going through the code to disable a certain section of a single filter. I guess I should have elaborated more earlier. I only mentioned it here because I'm not great with web uis (my friend used to do everything visual, I would always do the backend work), and incase it would help anyone else

**Comment by Dreamsorcerer** [comment]
Yeah, I just think that once you've experimented and got the filters working correctly, you're unlikely to need to disable parts of a filter. So, I don't think it's worth putting any time into trying to build the UI to handle all that. It might also introduce some latency with the extra function calls (probably negligible if compiled with mypyc though).

**Comment by rikka-chunibyo** [comment]
Yeah that's a good point, alright. There's just so many things I'm thinking of adding, none of which is extremely useful but can definetly help out in some cases. Maybe even a toggle to make keyboards report what you click in the ui as byte code so you don't need a print statement in your filter to test it out, my minds just cycling through ideas. Anyways if you ever figure out anything about this please mention me, I would like to be able to use mice without a Pi Zero

> ```
> pi@bthidhub:~/bthidhub/filters $ sudo hcitool sr 28:F0:76:4A:E4:F5 master
> Switch role request failed: Input/output error
> ```

**Comment by Dreamsorcerer** [comment]
> Maybe even a toggle to make keyboards report what you click in the ui as byte code so you don't need a print statement in your filter to test it out

#9, as you've already seen. The UI can just display the byte strings.

> Anyways if you ever figure out anything about this please mention me,

I don't know anything about it, so you'll probably have to do some searches, ask stackoverflow or open an issue with hcitool to figure out. I think the command to see the current status is `sudo hcitool con` and it'll show `PERIPHERAL` in slave mode.

**Comment by rikka-chunibyo** [comment]
Right, Forgot about that already, Pretty sure I read that at like 1am.

Okay I'll look into it

**Comment by rikka-chunibyo** [comment]
> > The specs are better on my Pi (4B 8GB Model) than the Pi Zero W, so if it's about specs than I don't think that's the problem
> 
> Yeah, that's what I'm confused by, I've no idea what the difference is. We had a previous report that the Pi 2 is moderately laggy and I guessed it might be performance as it has a 900Mhz CPU vs the Zero's 1GHz. But, the Pi 4 should be significantly faster...
> 
> Thinking back to other times I've had lag, there is the possibility it failed to set the device to master mode... You should see these print statements in the journalctl log:
> 
> [bthidhub/bluetooth_devices.py](https://github.com/Dreamsorcerer/bthidhub/blob/0172b35c64efcedf7f2eeb74bb87d554042e79f5/bluetooth_devices.py#L215-L220)
> 
> Lines 215 to 220 in [0172b35](/Dreamsorcerer/bthidhub/commit/0172b35c64efcedf7f2eeb74bb87d554042e79f5)
> 
>  print("switch to master called for ", device_address) 
>  while await self.is_slave(device_address): 
>      try: 
>          proc = await asyncio.create_subprocess_exec("sudo", "hcitool", "sr", device_address, "master", stdout=DEVNULL, stderr=sys.stderr) 
>          await proc.wait() 
>          print("hcitool ", device_address, " success:", proc.returncode == 0) 
> You can also use hcitool on the Pi to inspect the connection. You're looking for the laptop and verifying that it's set to MASTER and not SLAVE (or similar terminology).

It just clicked in, if it's a peripheral, why is the code trying to set it to master mode, peripheral are always slaves are they not?

**Comment by rikka-chunibyo** [comment]
> I get this while installing then it hangs for a while (got it last time too) `sudo: unable to resolve host rpi-hid: Name or service not known`, it continues seemingly fine though.

`sudo: unable to resolve host raspberrypi: Name or service not known`

Seems like it tries to resolve the pre-set host before it changes it

**Comment by Dreamsorcerer** [comment]
> Seems like it tries to resolve the pre-set host before it changes it, doesn't seem like much of a problem but it slows down the installation

I don't think it has any impact on speed, whatever is causing the issue. That's probably the last thing logged before mypyc compiles the code, which probably doesn't log anything and takes upto 20 mins.

**Comment by Dreamsorcerer** [comment]
> after maybe 5-10 minutes it disconnects from bluetooth and thats when problems start

I'm not clear exactly what problems? Biggest issue I experience currently, is that I seem to need to forget and re-pair my laptop every day or so otherwise it won't connect...

**Comment by rikka-chunibyo** [comment]
> I don't think it has any impact on speed, whatever is causing the issue. That's probably the last thing logged before mypyc compiles the code, which probably doesn't log anything and takes upto 20 mins.

On my Pi the installation is much fadter than an hour and mypyc takes around 5-10 minutes. But It seems like it just pauses after, unless mypyc doesn't log anything at the start


> > after maybe 5-10 minutes it disconnects from bluetooth and thats when problems start
> 
> I'm not clear exactly what problems? Biggest issue I experience currently, is that I seem to need to forget and re-pair my laptop every day or so otherwise it won't connect...

Yeah I get that a lot too, but after I've used it and restarted it a few times it stops connecting all together and I start getting some of the errors I've been describing.

On a different note, there's also a thing on mac where when you click the bluetooth icon it lists some devices, but for some reason after the Pi disconnects it's not there anymorr, and I have to go to bluetooth preferences and double click it there (I think it's also greyed out it in menu)

**Comment by Dreamsorcerer** [comment]
> On a different note, there's also a thing on mac where when you click the bluetooth icon it lists some devices, but for some reason after the Pi disconnects it's not there anymore, and I have to go to bluetooth preferences and double click it there to connect (I think it's also greyed out, but connects anyways)

I thought that just listed connected devices... No idea what difference could cause it to disappear if other devices don't.

> Yeah I get that a lot too, but after I've used it and restarted it a few times it stops connecting all together and I start getting some of the errors I've been describing.

Remember to check the bluetooth log. In one weird case, I think I found a device was paired but not authorised and I had to manually authorise it in bluetoothctl (the code should do it, but I guess something went weird that time).

**Comment by Dreamsorcerer** [comment]
> But It seems like it just pauses after, unless mypyc doesn't log anything at the start

I don't think it prints anything while it's working successfully.

**Comment by rikka-chunibyo** [comment]
> I thought that just listed connected devices... No idea what difference could cause it to disappear if other devices don't.
I thought that too, I've never seen any other devices disappear from the list, even devices that haven't been connect in months still show up

> Remember to check the bluetooth log. In one weird case, I think I found a device was paired but not authorised and I had to manually authorise it in bluetoothctl (the code should do it, but I guess something went weird that time).
Oh right, next time I get a problem I'll check it. I have noticed when pairing with the mac it asks to authorize but the prompt on both the mac and the web interface go away, I ahve been able to click the prompts once though, don't remember what I did differently

> I don't think it prints anything while it's working successfully.
I guess it's fine then

**Comment by Dreamsorcerer** [comment]
> I have noticed when pairing with the mac it asks to authorize but the prompts on both the mac and the web interface go away before I can click anything.

I've seen similar behaviour, though not as much recently. I think that could be related to getting into the paired/unauthorised state, but really not sure why it happens..

**Comment by rikka-chunibyo** [comment]
Would you like me to screen record it and supply the logs?

**Comment by Dreamsorcerer** [comment]
I've seen the behaviour myself, so not sure that helps. Unless there's an exception I missed...

**Comment by rikka-chunibyo** [comment]
I doubt there's much of a difference, I was thinking since the hardware seems to make a difference, but bluetooth still seems to act the same if you've seen it happen too

**Comment by Dreamsorcerer** [comment]
I'm no expert with BT/bluez, so I've really no idea what's going wrong. It probably doesn't help that we're using a hacked version of bluez either (https://github.com/Dreamsorcerer/bluez/commit/869c8a19d12287da43b2021732d5cd226342b82d), but I don't know enough to look into BT issues further.

**Comment by rikka-chunibyo** [comment]
I thought you would know more about it considering you were able to make that fork at all, either way it doesn't seem to be a problem in my case, or at least I don't think it's related to the other problems, maybe it disappearing from the bluetooth menu but that's probably something to do with how macos monetery handles bluetooth

**Comment by Dreamsorcerer** [comment]
> I thought you would know more about it considering you were able to make that fork at all

That was all ruundii, before I got involved. You can see the individual changes in https://github.com/Dreamsorcerer/bluez/commits/changelog/
Only thing I've done is just about figured out how to change the logic to decide if a device is a host or not. Not even sure what it was doing before (but all my devices stopped getting recognised as hosts), but I managed to replace it with something that literally just checks the device class to see if it is a phone or computer.

**Comment by rikka-chunibyo** [comment]
Yeah that makes sense, I sorta go about things like that too. I don't fully understand stand the things I often work on ¯\\\_(ツ)_/¯

**Comment by rikka-chunibyo** [comment]
I found another problem with it, because it disappears from the immediate list of bluetooth devices (it's visible in the expanded list in preferences but not in the list you get when you click the bluetooth icon in the top bar), it doesn't reconnect automatically, not a huge deal initially but after bringing the device out of sleep mode, you can't type your password since it doesn't reconnect automatically

**Comment by Dreamsorcerer** [comment]
Yep, that's something I was planning to look at (don't think it's related to the presence of the dropdown though). Probably we want to reconnect to hosts in the code. e.g. If input events are received, but no host is connected, then it should iterate through the hosts and try to connect them.

**Comment by rikka-chunibyo** [comment]
Actually now that I think about it, yeah, your definitely right. If I click connect on the site it can connect to the mac without me even touching it, so yeah auto connect should be handled from the Pi

**Comment by rikka-chunibyo** [comment]
Don't know what changed but mouse is usable now, very choppy but actually tolerable for imprecise movements

**Comment by rikka-chunibyo** [comment]
My Pi Zero 2 W should arrive tmr so I can see if the lag is caused by the mouse or the Pi. As well as any other problems.

I also just want to mention this priject would be amazing on a Pi 400! You'd have a bluetooth keyboard and can turn a wired mouse into a wireless one, with a built-in KVM (minus video), and it would also be remappable.

**Comment by rikka-chunibyo** [comment]
Same lag, nothing else changed, so it's probably the mouse.

**Comment by rikka-chunibyo** [comment]
Before I test, could you make a branch with pr #26 and the updated dependancies? I can't use any of my keyboards at the moment, I had to use previous sd card with my other test but I already wiped that one...

**Comment by Dreamsorcerer** [comment]
I merged master into it, if that's what you mean.

**Comment by rikka-chunibyo** [comment]
Yeah, thanks

**Comment by rikka-chunibyo** [comment]
Oh, same thing happened, didn't fix the dependancies

```
Mar 17 00:03:35 bthidhub systemd[1]: Started remapper.service - Remapper.
░░ Subject: A start job for unit remapper.service has finished successfully
░░ Defined-By: systemd
░░ Support: https://www.debian.org/support
░░
░░ A start job for unit remapper.service has finished successfully.
░░
░░ The job identifier is 119.
Mar 17 00:03:36 bthidhub python3[506]: Traceback (most recent call last):
Mar 17 00:03:36 bthidhub python3[506]:   File "/home/pi/bthidhub/remapper.py", line 7, in <module>
Mar 17 00:03:36 bthidhub python3[506]:     from dasbus.connection import SystemMessageBus
Mar 17 00:03:36 bthidhub python3[506]: ModuleNotFoundError: No module named 'dasbus'
Mar 17 00:03:36 bthidhub systemd[1]: remapper.service: Main process exited, code=exited, status=1/FAILURE
░░ Subject: Unit process exited
░░ Defined-By: systemd
░░ Support: https://www.debian.org/support
░░
░░ An ExecStart= process belonging to unit remapper.service has exited.
░░
░░ The process' exit code is 'exited' and its exit status is 1.
Mar 17 00:03:36 bthidhub systemd[1]: remapper.service: Failed with result 'exit-code'.
░░ Subject: Unit failed
░░ Defined-By: systemd
░░ Support: https://www.debian.org/support
░░
░░ The unit remapper.service has entered the 'failed' state with result 'exit-code'.
lines 2-34/34 (END)
```

Starts out with that package then progresses up to where I get stuck, 'girepository' or something like that

By the way, you should start shying away from hardcoded paths, it's quite annoying to accomplish anything when you can't even rename a directory

**Comment by rikka-chunibyo** [comment]
Actually I think I know what caused the apt install to fail, I've had this happen a lot recently. It takes a bit for raspian to set the time, and if you try installing before it sets the time, it fails

**Comment by rikka-chunibyo** [comment]
Nevermind, that was the issue the first time but other times it was because I'm not using the setup.sh file, since I'm using a pr I'm avoiding that. I just need to apt update and install git beforehand. I was having problems with bluetooth, no logs about it though.

```
pi@bthidhub:~ $ sudo hcitool con
Connections:
	> ACL 28:F0:76:4A:E4:F5 handle 11 state 1 lm PERIPHERAL AUTH ENCRYPT
```

Also tried another mouse and it was even laggier

**Comment by Dreamsorcerer** [comment]
That's in slave mode though. Does setting it to master not work again?

**Comment by rikka-chunibyo** [comment]
I'll try later today, forgot to actually run it

**Comment by rikka-chunibyo** [comment]
```
pi@bthidhub:~ $ sudo hcitool dev
Devices:
	hci0	B8:27:EB:9D:CD:0A
pi@bthidhub:~ $ sudo hcitool sr B8:27:EB:9D:CD:0A master
Not connected.
pi@bthidhub:~ $
```

Am I listing devices wrong?
